root: true
parser: "@typescript-eslint/parser"
plugins:
  - jest
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
